fail_fast: false
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline', 'force-use-all-plugins']
        exclude: .*\.lock*|.*\.md|.secrets.baseline
  - repo: local
    hooks:
      - id: talisman-precommit
        name: talisman
        entry: >-
          bash -c 'if [ -n "${TALISMAN_HOME:-}" ];
          then TALISMAN_INTERACTIVE=false ${TALISMAN_HOME}/talisman_hook_script pre-commit;
          else echo "TALISMAN does not exist.
          Consider installing from https://github.com/thoughtworks/talisman .
          If you already have talisman installed, please ensure TALISMAN_HOME
          variable is set to where talisman_hook_script resides, for example,
          TALISMAN_HOME=${HOME}/.talisman/bin";
          fi'
        language: system
        pass_filenames: false
        types: [text]
        verbose: true
